input {
  beats {
    port => 5044
  }
}

filter {
  if [agent][type] == "winlogbeat" {
    mutate {
      add_field => { "log_source" => "windows" }
    }
  }

  if [agent][type] == "filebeat" {
    mutate {
      add_field => { "log_source" => "linux" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    user => "elastic"
    password => "${ELASTIC_PASSWORD}"
    index => "siem-%{log_source}-%{+yyyy.MM.dd}"
  }
}
